package com.fetutex.retirement;


import java.util.*;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;


/***************************************************************************
 * ViewClass.java
 *
 * This program is used to finance and plan an individual's fetutex retirement.
 * This is the view and controller for this application.
 * 
 * @category Computer Science 368
 * @version 2.3
 ***************************************************************************/
public class ViewClass extends javax.swing.JApplet implements Observer {

	//autogenerated serialVersionUID
	private static final long serialVersionUID = -2531844655242885628L;

	// creates an instance of the model class to implement MVC
	private ModelClass theModel;


	/***************************************************************************
	 * Initializes the applet ViewClass
	 ***************************************************************************/
	public void init() {
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {

				/***************************************************************
				 * Calls the run method to create the view of the applet.
				 ***************************************************************/
				public void run(){
					initComponents();
				}

			});

			ModelClass model = new ModelClass();
			theModel = model;
			theModel.addObserver(this);

		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		
			
		}
 @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">  
/***************************************************************************
 * This method is called from within the init() method to
 * initialize the form.
 * 
 * This code was autogenerated from NetBeans
 ***************************************************************************/
private void initComponents() {

	buttonGroup1 = new javax.swing.ButtonGroup();
	jTextField1 = new javax.swing.JTextField();
	jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jTextField3 = new javax.swing.JTextField();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jTextField4 = new javax.swing.JTextField();
	jLabel5 = new javax.swing.JLabel();
	jButton1 = new javax.swing.JButton();
	jButton2 = new javax.swing.JButton();
	jTextField6 = new javax.swing.JTextField();
	jTextField7 = new javax.swing.JTextField();
	jTextField8 = new javax.swing.JTextField();
	jTextField9 = new javax.swing.JTextField();
	jTextField10 = new javax.swing.JTextField();
	jLabel6 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	jLabel9 = new javax.swing.JLabel();
	jLabel10 = new javax.swing.JLabel();
	jLabel11 = new javax.swing.JLabel();
	jLabel12 = new javax.swing.JLabel();
	jComboBox1 = new javax.swing.JComboBox();
	jComboBox2 = new javax.swing.JComboBox();
	jButton3 = new javax.swing.JButton();
	jSpinner2 = new javax.swing.JSpinner();
	jLabel13 = new javax.swing.JLabel();
	jLabel14 = new javax.swing.JLabel();
	jComboBox3 = new javax.swing.JComboBox();
	jLabel15 = new javax.swing.JLabel();
	jTextField2 = new javax.swing.JTextField();
	jLabel16 = new javax.swing.JLabel();
	jLabel17 = new javax.swing.JLabel();
	jTextField11 = new javax.swing.JTextField();
	jTextField12 = new javax.swing.JTextField();
	jTextField13 = new javax.swing.JTextField();
	jFormattedTextField1 = new javax.swing.JFormattedTextField();
	jScrollBar1 = new javax.swing.JScrollBar();
	jRadioButton1 = new javax.swing.JRadioButton();
	jRadioButton2 = new javax.swing.JRadioButton();
	jLabel18 = new javax.swing.JLabel();
	jLabel19 = new javax.swing.JLabel();
	jLabel20 = new javax.swing.JLabel();
	
	setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	setStub(null);

	jTextField1.setToolTipText("Your first and last name.");
	jTextField1.setPreferredSize(new java.awt.Dimension(100, 20));

	jLabel1.setText("Name");

	jLabel2.setText("Birthdate (mm/dd/yyyy)");

	jTextField3.setToolTipText("Your current annual income.");
	jTextField3.setPreferredSize(new java.awt.Dimension(100, 20));

	jLabel3.setText("Annual Income");

	jLabel4.setText("Social Security Income");

	jTextField4.setEditable(false);
	jTextField4.setToolTipText("Income received annually from social security");
	jTextField4.setPreferredSize(new java.awt.Dimension(100, 20));

	jButton1.setText("Calculate");
	jButton1.setToolTipText("Performs the calculations needed to compute annual amount needed to reach your goal.");
	jButton1.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jButton1ActionPerformed(evt);
		}
	});

	jButton2.setText("Reset");
	jButton2.setToolTipText("Sets all fields to its default value");
	jButton2.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jButton2ActionPerformed(evt);
		}
	});
	jTextField6.setToolTipText("Income received annually from other sources (such as pension plans, earnings on assets, part-time job, etc.)");
	jTextField6.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			//jTextField6ActionPerformed(evt);
		}
	});

	jTextField7.setEditable(false);
	jTextField7.setToolTipText("This is how much you need to make up for each retirement year");

	jTextField8.setToolTipText("Total Savings to date (include money accumulated in a 401(k), IRA, or similar retirement plan)");
	jTextField8.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			//jTextField8ActionPerformed(evt);
		}
	});

	jTextField9.setEditable(false);
	jTextField9.setToolTipText("The total amount of savings needed when you retire.");

	jTextField10.setEditable(false);
	jTextField10.setToolTipText("Annual amount you'll need to save each year to earn the specified percentage of your income.");

	jLabel6.setText("Other (earnings on assets etc.)");

	jLabel7.setText("Annual Retirement funds needed");

	jLabel8.setText("Expected Retirement Age");

	jLabel9.setText("Life Expectancy");

	jLabel10.setText("Total Amount In Savings");

	jLabel11.setText("Total Savings Needed at Retirement");

	jLabel12.setText("ANNUAL AMOUNT NEEDED");

	jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "55-59", "60-64", "65-69", "70+" }));
	jComboBox1.setToolTipText("Age at which you expect to retire");

	jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Below Average", "Average", "Above Average" }));
	jComboBox2.setToolTipText("Life Expectancy:\n(The average male life expectancy is 89)\n(The average female life expectany is 92)");

	jButton3.setText("Print");
	jButton3.setToolTipText(" Brings up a read-only dialog showing a summary of the resulting plan in a printable form");
	jButton3.addActionListener(new java.awt.event.ActionListener() {
		public void actionPerformed(java.awt.event.ActionEvent evt) {
			jButton3ActionPerformed(evt);
		}
	});




	