package com.fetutex.retirement;


import java.util.*;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;


/***************************************************************************
 * ViewClass.java
 *
 * This program is used to finance and plan an individual's fetutex retirement.
 * This is the view and controller for this application.
 * 
 * @category Computer Science 368
 * @version 2.3
 ***************************************************************************/
public class ViewClass extends javax.swing.JApplet implements Observer {

	//autogenerated serialVersionUID
	private static final long serialVersionUID = -2531844655242885628L;

	// creates an instance of the model class to implement MVC
	private ModelClass theModel;


	/***************************************************************************
	 * Initializes the applet ViewClass
	 ***************************************************************************/
	public void init() {
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {

				/***************************************************************
				 * Calls the run method to create the view of the applet.
				 ***************************************************************/
				public void run(){
			//		initComponents();
				}

			});

			ModelClass model = new ModelClass();
			theModel = model;
			theModel.addObserver(this);

		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}}


	