package com.fetutex.retirement;


import java.util.*;
import java.awt.Color;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;


/***************************************************************************
 * ViewClass.java
 *
 * This program is used to finance and plan an individual's fetutex retirement.
 * This is the view and controller for this application.
 * 
 * @category Computer Science 368
 * @version 2.3
 ***************************************************************************/
public class ViewClass extends javax.swing.JApplet implements Observer {

	//autogenerated serialVersionUID
	private static final long serialVersionUID = -2531844655242885628L;

	// creates an instance of the model class to implement MVC
	private ModelClass theModel;


	/***************************************************************************
	 * Initializes the applet ViewClass
	 ***************************************************************************/
	public void init() {
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {

				/***************************************************************
				 * Calls the run method to create the view of the applet.
				 ***************************************************************/
				public void run(){
					initComponents();
				}

			});

			ModelClass model = new ModelClass();
			theModel = model;
			theModel.addObserver(this);

		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		
			
		}
 @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">  
/***************************************************************************
 * This method is called from within the init() method to
 * initialize the form.
 * 
 * This code was autogenerated from NetBeans
 ***************************************************************************/
private void initComponents() {

	buttonGroup1 = new javax.swing.ButtonGroup();
	jTextField1 = new javax.swing.JTextField();
	jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jTextField3 = new javax.swing.JTextField();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jTextField4 = new javax.swing.JTextField();
	jLabel5 = new javax.swing.JLabel();
	jButton1 = new javax.swing.JButton();
	jButton2 = new javax.swing.JButton();
	jTextField6 = new javax.swing.JTextField();
	jTextField7 = new javax.swing.JTextField();
	jTextField8 = new javax.swing.JTextField();
	jTextField9 = new javax.swing.JTextField();
	jTextField10 = new javax.swing.JTextField();
	jLabel6 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	jLabel9 = new javax.swing.JLabel();
	jLabel10 = new javax.swing.JLabel();
	jLabel11 = new javax.swing.JLabel();
	jLabel12 = new javax.swing.JLabel();
	jComboBox1 = new javax.swing.JComboBox();
	jComboBox2 = new javax.swing.JComboBox();
	jButton3 = new javax.swing.JButton();
	jSpinner2 = new javax.swing.JSpinner();
	jLabel13 = new javax.swing.JLabel();
	jLabel14 = new javax.swing.JLabel();
	jComboBox3 = new javax.swing.JComboBox();
	jLabel15 = new javax.swing.JLabel();
	jTextField2 = new javax.swing.JTextField();
	jLabel16 = new javax.swing.JLabel();
	jLabel17 = new javax.swing.JLabel();
	jTextField11 = new javax.swing.JTextField();
	jTextField12 = new javax.swing.JTextField();
	jTextField13 = new javax.swing.JTextField();
	jFormattedTextField1 = new javax.swing.JFormattedTextField();
	jScrollBar1 = new javax.swing.JScrollBar();
	jRadioButton1 = new javax.swing.JRadioButton();
	jRadioButton2 = new javax.swing.JRadioButton();
	jLabel18 = new javax.swing.JLabel();
	jLabel19 = new javax.swing.JLabel();
	jLabel20 = new javax.swing.JLabel();


	